# Generated by Django 2.2.5 on 2019-09-26 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('path', models.TextField()),
                ('referrer', models.TextField(blank=True)),
                ('user_hash', models.TextField()),
                ('is_authenticated', models.BooleanField()),
            ],
        ),
    ]
