# Generated by Django 3.0.2 on 2020-05-09 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('path', models.TextField()),
                ('referrer', models.TextField(blank=True)),
                ('session_key', models.TextField()),
                ('is_authenticated', models.BooleanField()),
            ],
        ),
    ]
