# Generated by Django 2.2.5 on 2019-09-26 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('privacy_analytics', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Visit',
            new_name='PageView',
        ),
    ]
